[[language]]
name = "roc"
auto-format = true
scope = "source.roc"
injection-regex = "roc"
file-types = ["roc"]
comment-tokens = "#"
indent = { unit = "    ", tab-width = 4 }
language-servers = ["roc-language-server"]

[language-server.roc-language-server]
command = "roc_language_server"

[[grammer]]
name = "roc"
source = { git = "https://github.com/faldor20/tree-sitter-roc.git", rev = "7d29fc24b36119494b4dc3f3d967075e261706c1" }

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "scheme"
auto-format = true
formatter = { command = "lua", args = ["/home/kilianvounckx/.config/helix/parinfer-lua/parinfer.lua"] }
language-servers = ["steel-language-server"]

[language-server.steel-language-server]
command = "steel-language-server"

[[language]]
name = "haskell"
auto-format = true

[[language]]
name = "ocaml"
auto-format = true

[language-server.ucm]
command = "nc"
args = ["localhost", "5757"]

[[language]]
name = "unison"
scope = "source.unison"
injection-regex = "unison"
file-types = ["u"]
shebangs = []
roots = []
auto-format = false
comment-token = "--"
indent = { tab-width = 4, unit = "    " }
language-servers = [ "ucm" ]
